// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mentor_backend.Data;

namespace mentor_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190623082137_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("mentor_backend.Models.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("TeachingInformation");

                    b.HasKey("Id");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("mentor_backend.Models.Price", b =>
                {
                    b.Property<int>("Id");

                    b.Property<double>("Price30Min");

                    b.Property<double>("Price45Min");

                    b.Property<double>("Price60Min");

                    b.HasKey("Id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("mentor_backend.Models.Price", b =>
                {
                    b.HasOne("mentor_backend.Models.Mentor", "Mentor")
                        .WithOne("Price")
                        .HasForeignKey("mentor_backend.Models.Price", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
